version: "3"

services:
  redis:
    image: redis
  
  shorten:
    build: .
    image: ghcr.io/ledo01/shorten:1.0.0
    environment:
      - SERVER_PORT=3000
      - DB_URL=redis://redis:6379
    ports:
      - 3000:3000